version: '3'

services:
    app:
        build: .
        image: cobaltcaboose/bbmachine:1.0
        ports:
            - 80:8000
        volumes:
            - .:/app
    cron:
        build: ./cron

